chore: Add production section to example app
pagopa/io-react-native-wallet pull request #74
Opened 2024-04-22 13:08 UTC by grausof

Adds a new section to the sample app by splitting the screen between PoC and Production.

<img width="386" alt="Screenshot 2024-04-22 at 15 06 30" src="https://github.com/pagopa/io-react-native-wallet/assets/442709/fdda0d21-d18d-4be8-ba5f-c482a186da7c">

2024-05-07 08:47 UTC, LazyAfternoons commented on example/src/App.tsx
> +          })}
Small suggestion here, we could extract this function like this: 
`const bottomBar = (
    route: RouteProp<RootStackParamList, keyof RootStackParamList>
  ) => {
    let icon;
    if (route.name === "PoC") {
      icon = "🧪";
    } else if (route.name === "Production") {
      icon = "🚀";
    }
    return <Text>{icon}</Text>;
  };`
  
  And use it like: 
`tabBarIcon: () => bottomBar(route),`

2024-05-07 08:52 UTC, LazyAfternoons requested changes

2024-05-07 08:52 UTC, LazyAfternoons commented on example/src/App.tsx
We could use `SafeAreaView` exported by `react-native-safe-area-context` which you already added as dependency as it also works on Android, rather than the standard export from `react-native` which only works on iOS. 

I would also remove the `marginHorizontal` from the `container` style as it adds it also around the tab bar. Maybe we could add it in an inner view only for the content of the screen, leaving the tab bar out. 

Small changes but let me know what you think.

2024-05-08 13:55 UTC, grausof commented on example/src/App.tsx
That's right, you're a React ninja 🥷.
I added a `SafeAreaProvider` and a `SafeAreaView` from `react-native-safe-area-context`. 
Let me know if it is okay!

2024-05-09 09:01 UTC, hevelius requested changes

2024-05-09 09:31 UTC, hevelius approved these changes
LGTM. @LazyAfternoons please check if your conversations can be resolved.

2024-05-13 08:35 UTC, LazyAfternoons reviewed
LGTM

2024-05-14 07:26 UTC, merged