feat: Add Wallet Instance Attestation issuing [SIW-314,315]
pagopa/io-react-native-wallet pull request #8
Opened 2023-07-19 14:32 UTC by grausof

Adds Wallet Instance integration and issuing.

#### List of Changes
- Added Wallet Instance Attestation Request
- Added Wallet Instance issuing
- Changed default npm registry
- Added example app with TEE

#### How Has This Been Tested?
unit tested and tested on simulator

2023-07-19 16:00 UTC, hevelius requested changes

2023-07-20 07:05 UTC, grausof commented on src/wallet-instance-attestation/issuing.ts
> +    type: "WalletInstanceAttestationRequest",
This is a unique and immutable value for everyone. There cannot be a different value!

2023-07-20 07:37 UTC, grausof commented on src/index.ts
> +  "https://io-d-wallet-it.azurewebsites.net";
I agree with you, I tried adding it as an initialization parameter of the `Issuing` class

2023-07-20 07:42 UTC, hevelius approved these changes
LGTM

2023-07-20 07:44 UTC, merged